### ISSUE TITLE
I present to you: ringlet -- another tool inspired by Ross's concept

### ISSUE THREAD

**Issue by miezebieze** [HawaiinPizza/Rational-Operating-System-Shell#9]
After a shitty prototype with pygame I learnt Xlib and rewrote everything.

https://github.com/miezebieze/ringlet

I have a bare minimum window with customizable selector pads that can call arbitrary functions on touching them with the mouse pointer.

The DEVME.md contains a collection of ideas.

**Comment by arawnx** [comment]
Interesting; is it a MVP or in-dev? If it's working I think we'd like to appropriate some of your concepts–that is, contribute or else borrow. It's in python which may make certain functionality more abstruse (and in Xlib rather than XCB, a predilection I'm not certain we'll maintain) and slow, but if it's raw X bindings then there shouldn't be any cost in speed.

**Comment by miezebieze** [comment]
It's in-dev and I haven't really gotten into Xlib.
Feel free to contribute/borrow whereever you like.
I'm doing the best I can to make it as easy to understand and modify as possible. 
I'm looking into XCB as well. If you think that's better I can go with it. I haven't put much energy into learning Xlib, yet, so I can still feel comfortable to switch.
To battle the relative low speed of python I thought about using pypy. It really speeds up things.

**Comment by arawnx** [comment]
XCB seems like it may be the wrong choice since it's extraordinarily low level, which is usually not a problem, but it has exceptionally poor documentation as well. I'll check out your repo, thanks!
